### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by juancarlosgl**
This PR adds dependabot yaml file so this project runs a job to verify if there is any vulnerability with its dependencies

[RAD-2540](https://radixiot.atlassian.net/browse/RAD-2540) 

[RAD-2540]: https://radixiot.atlassian.net/browse/RAD-2540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terrypacker** [comment]
@juancarlosgl how can we know it works and is there any risk with this?  @kubeliv will these jobs only run on the default branch or should be see some results from this branch?

**Comment by kubeliv** [comment]
> @juancarlosgl how can we know it works and is there any risk with this? @kubeliv will these jobs only run on the default branch or should be see some results from this branch?

The way that the schedule workflow works is that it only pays attention to those on the default branch. https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
The risks here are if someone were to merge a malicious workflow, they could access our organization secrets for ones that are accessible to all repositories.

**Review by terrypacker — COMMENTED** [review]
Is the JIRA_WATCHERS correct?

**Comment by juancarlosgl** [comment]
> Is the JIRA_WATCHERS correct? 
Yes I will do Benjamin's Projects asignes

**Review by terrypacker — APPROVED** [review]

**Comment by juancarlosgl** [comment]
> Is the JIRA_WATCHERS correct? 
Yes I will do Benjamin's Projects asignes

**Pull request merged**
